In [2]:
import pandas as pd
import numpy as np

In [5]:
data = pd.read_csv('powerplant.csv')
data.columns

Index(['country', 'country_long', 'name', 'gppd_idnr', 'capacity_mw',
       'latitude', 'longitude', 'primary_fuel', 'other_fuel1', 'other_fuel2',
       'other_fuel3', 'commissioning_year', 'owner', 'source', 'url',
       'geolocation_source', 'wepp_id', 'year_of_capacity_data',
       'generation_gwh_2013', 'generation_gwh_2014', 'generation_gwh_2015',
       'generation_gwh_2016', 'generation_gwh_2017',
       'estimated_generation_gwh'],
      dtype='object')

In [9]:
data1 = data[['country_long', 'name', 'capacity_mw', 'latitude', 'longitude', 'primary_fuel','commissioning_year', 'owner']]
data1

,country_long,name,capacity_mw,latitude,longitude,primary_fuel,commissioning_year,owner
0,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.00,32.3220,65.1190,Hydro,NaN,NaN
1,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.00,34.5560,69.4787,Hydro,NaN,NaN
2,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.00,34.6410,69.7170,Hydro,NaN,NaN
3,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,11.55,34.4847,70.3633,Hydro,NaN,NaN
4,Afghanistan,Northwest Kabul Power Plant Afghanistan,42.00,34.5638,69.1134,Gas,NaN,NaN
...,...,...,...,...,...,...,...,...
29905,Zambia,Ndola,50.00,-12.9667,28.6333,Oil,NaN,ZESCO
29906,Zambia,Nkana,20.00,-12.8167,28.2000,Oil,NaN,ZESCO
29907,Zambia,Victoria Falls,108.00,-17.9167,25.8500,Hydro,NaN,ZESCO
29908,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.00,-18.3835,26.4700,Coal,NaN,NaN
29909,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.00,-16.5222,28.7619,Hydro,NaN,NaN

In [12]:
data1['commissioning_year'] = data1['commissioning_year'].fillna('non_communique')
data1.head(10)

<ipython-input-12-ecfaa5378db5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['commissioning_year'] = data1['commissioning_year'].fillna('non_communique')

,country_long,name,capacity_mw,latitude,longitude,primary_fuel,commissioning_year,owner
0,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.00,32.3220,65.1190,Hydro,non_communique,NaN
1,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.00,34.5560,69.4787,Hydro,non_communique,NaN
2,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.00,34.6410,69.7170,Hydro,non_communique,NaN
3,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,11.55,34.4847,70.3633,Hydro,non_communique,NaN
4,Afghanistan,Northwest Kabul Power Plant Afghanistan,42.00,34.5638,69.1134,Gas,non_communique,NaN
5,Afghanistan,Pul-e-Khumri Hydroelectric Power Plant Afghani...,6.00,35.9416,68.7100,Hydro,non_communique,NaN
6,Afghanistan,Sarobi Dam Hydroelectric Power Plant Afghanistan,22.00,34.5865,69.7757,Hydro,non_communique,NaN
7,Albania,Bistrica 1,27.00,39.9116,20.1047,Hydro,1965,NaN
8,Albania,Fierza,500.00,42.2514,20.0431,Hydro,1978,NaN
9,Albania,Koman,600.00,42.1033,19.8224,Hydro,1985,NaN

In [13]:
data1['owner'] = data1['owner'].fillna('state')
data1

<ipython-input-13-2d71bf98f26d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data1['owner'] = data1['owner'].fillna('state')

,country_long,name,capacity_mw,latitude,longitude,primary_fuel,commissioning_year,owner
0,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.00,32.3220,65.1190,Hydro,non_communique,state
1,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.00,34.5560,69.4787,Hydro,non_communique,state
2,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.00,34.6410,69.7170,Hydro,non_communique,state
3,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,11.55,34.4847,70.3633,Hydro,non_communique,state
4,Afghanistan,Northwest Kabul Power Plant Afghanistan,42.00,34.5638,69.1134,Gas,non_communique,state
...,...,...,...,...,...,...,...,...
29905,Zambia,Ndola,50.00,-12.9667,28.6333,Oil,non_communique,ZESCO
29906,Zambia,Nkana,20.00,-12.8167,28.2000,Oil,non_communique,ZESCO
29907,Zambia,Victoria Falls,108.00,-17.9167,25.8500,Hydro,non_communique,ZESCO
29908,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.00,-18.3835,26.4700,Coal,non_communique,state
29909,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.00,-16.5222,28.7619,Hydro,non_communique,state

In [15]:
data2 = data1.dropna()
data2

,country_long,name,capacity_mw,latitude,longitude,primary_fuel,commissioning_year,owner
0,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,33.00,32.3220,65.1190,Hydro,non_communique,state
1,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,66.00,34.5560,69.4787,Hydro,non_communique,state
2,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,100.00,34.6410,69.7170,Hydro,non_communique,state
3,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,11.55,34.4847,70.3633,Hydro,non_communique,state
4,Afghanistan,Northwest Kabul Power Plant Afghanistan,42.00,34.5638,69.1134,Gas,non_communique,state
...,...,...,...,...,...,...,...,...
29905,Zambia,Ndola,50.00,-12.9667,28.6333,Oil,non_communique,ZESCO
29906,Zambia,Nkana,20.00,-12.8167,28.2000,Oil,non_communique,ZESCO
29907,Zambia,Victoria Falls,108.00,-17.9167,25.8500,Hydro,non_communique,ZESCO
29908,Zimbabwe,Hwange Coal Power Plant Zimbabwe,920.00,-18.3835,26.4700,Coal,non_communique,state
29909,Zimbabwe,Kariba Dam South Hydroelectric Power Station Z...,750.00,-16.5222,28.7619,Hydro,non_communique,state